### PR TITLE
file added.

### PR DESCRIPTION
**Pull request by MozhganPourKeshavarz**
I got this message again, "Can’t automatically merge."
could you check it again, please?
thanks.

### CODE REVIEW

**Comment by MozhganPourKeshavarz** [comment]
Oops, 
I will change it today ,
Thanks dear.

**Comment by sehsanm** [comment]
Hi Any Updateds ? 
I have not received anything from you after our last conversation

**Comment by MozhganPourKeshavarz** [comment]
Hi dear, 
Dr. Shamsfard said that you were going to update tag list, so I thought it would be changed,
I'll submit my output based on current tags till tomorrow of course,
thanks for your reminder.

**Comment by MozhganPourKeshavarz** [comment]
I submitted final outputs, and my reference will be uploaded till tomorrow,
but some guys made a lot of mistakes in their references, specially in verbs morphology.. 
for example 
"می‌خورند" --> v   
but it must be : "O+v1+O"

**Comment by MozhganPourKeshavarz** [comment]
Final files was added under last commit "Final outputs and reference file ", and there is no update.
looking forward to your reply.
thanks.

**Comment by sehsanm** [comment]
Hi 
You are right the tag are not as complete as we expected.  Also some ref files are not 100% correct. But what will happen is that the score that they get from their ref file will be low.  Each team will be scored based on two aspects how acceptable their Ref file is (based on what other teams will score on their input) and  scores that each team is earning on other team input. 


Also please note that since I merged your PR two days ago nothing been updated since then.

**Pull request merged**
