### PR TITLE
output files and reference file

### PR DESCRIPTION
**Pull request by kibamin**
Is my file extension (.ref) correct or should be change to(.out) ?

### CODE REVIEW

**Comment by sehsanm** [comment]
it should be ref file

**Comment by sehsanm** [comment]
Hi Amin, 
I thought you are talking about your own ref file. For others it should .out file. 

Sorry I misunderstood your question

**Comment by sehsanm** [comment]
Can you please resubmit it? 

If you cannot, I can rename your files.

**Comment by kibamin** [comment]
> Can you please resubmit it?
> 
> If you cannot, I can rename your files.

I resubmitted output files with ".out" extension.

But in your readme in **Phase III: Run your code** , this is written :
"Your output **files** must be stored in your own folder and the file name should be the same as the input file but **with .ref extension**."

**Comment by kibamin** [comment]
check my pull request ,please

**Pull request merged**
